[project]
name = "photobooth2"
version = "0.1.0"
requires-python = ">=3.14"

# ----------------------------
# Black
# ----------------------------
[tool.black]
line-length = 100
target-version = ["py313"]
skip-string-normalization = false

# ----------------------------
# Ruff
# ----------------------------
[tool.ruff]
line-length = 100
src = ["photobooth2"]
respect-gitignore = true

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

ignore = [
  "E203",   # Black slices
  "E501",   # Black entscheidet Zeilenlänge
  "SIM108", # if/else lesbarer als ternary (bewusst)
]

per-file-ignores = { "__init__.py" = ["F401"] }

[tool.ruff.lint.isort]
known-first-party = ["photobooth2"]
combine-as-imports = true

# ----------------------------
# Pylint (optional)
# ----------------------------
[tool.pylint.main]
py-version = "3.14"
jobs = 0

[tool.pylint.format]
max-line-length = 100

[tool.pylint.messages_control]
disable = [
  "C0114",
  "C0115",
  "C0116",
  "R0903",
]
